[package]
name = "pipeviewer"
version = "0.1.0"
authors = ["Stanislau Yanukou <stanislau.yanukou@enmacc.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
crossbeam = "0.7.3"
crossterm = "0.14.2"
